Sprint 3
aiilui93/middle.messenger.praktikum.yandex pull request #3
Opened 2022-12-24 23:59 UTC by aiilui93

2022-12-25 14:04 UTC, podlovchenko requested changes
Привет, по работе приложения все классно 👍 Есть несколько замечаний по коду
Пропсы для компонентов описаны типом Record<string, unknown>, который не говорит о том какие свойства можно передать в компонент и не поможет избежать ошибок
Также есть ошибки типизации, попробуй выполнить команду `npx tsc --noEmit`

2022-12-25 14:04 UTC, podlovchenko commented on src/api/ChatsAPI.ts
> +export default new ChatsAPI();
Использование дефолтных экспортов, на мой взгляд, это не очень хорошая практика.

Они позволяют задавать разные имена импортируемым объектам, из-за этого страдает читабельность, экземпляры с разными именами очень трудно потом искать по проекту. Так же затрудняется рефакторинг таких импортов.

Если задавать обычный экспорт, мы можем быть почти везде точно уверены, что имена используются везде одинаковые и IDE в таком случае спокойно их сможет поменять в случае рефакторинга.

Хорошая статья на эту тему
https://humanwhocodes.com/blog/2019/01/stop-using-default-exports-javascript-module/

2022-12-25 14:04 UTC, podlovchenko commented on src/api/UserAPI.ts
> +            });
Логика обработки ошибки повторяется в каждом методе,  лучше внести в HttpTransport

2022-12-25 14:04 UTC, podlovchenko commented on src/styles/popup.scss
> +        input {
Лучше использовать классы, а не теги
Статья на эту тему https://frontstuff.io/you-need-to-stop-targeting-tags-in-css

2022-12-25 14:04 UTC, podlovchenko commented on src/utils/HTTPTransport/HTTPTransport.ts
> +enum METHOD {
enum обычно именуется в формате PascalCase

2022-12-25 14:04 UTC, podlovchenko commented on src/utils/HTTPTransport/HTTPTransport.ts
> +type HTTPMethod = (url: string, options?: OptionsWithoutMethod) => Promise<unknown>
Можно сделать функцию дженериком, чтобы иметь возможность описать тип возвращаемого значения извне
```suggestion
type HTTPMethod = <Res>(url: string, options?: OptionsWithoutMethod) => Promise<Res>
```

2023-01-13 22:43 UTC, aiilui93 commented on src/api/UserAPI.ts
> +            });
Убрала обработку ошибок, она мне тут не нужна была)

2023-01-13 23:54 UTC, aiilui93 commented on src/api/ChatsAPI.ts
> +export default new ChatsAPI();
Привет) npx tsc --noEmit прогнала, пофиксила) 
Record<string, unknown> у меня местами встречается, но не везде, в 70% случаев я типизировала пропсы, просто уже времени не хватало на все компоненты, поэтому в менее значимых местах оставила так)
остальные правки внесла, только дефолтные экспорты не меняла, у нас их наставник использовал, я думала не так принципиально) но замечание приняла к сведению, менять всё на именованные экспорты сейчас запарно(

2023-01-13 23:55 UTC, aiilui93 commented on src/styles/popup.scss
> +        input {
заменила в данном случае на классы

2023-01-13 23:55 UTC, aiilui93 commented on src/utils/HTTPTransport/HTTPTransport.ts
> +enum METHOD {
+

2023-01-13 23:55 UTC, aiilui93 commented on src/utils/HTTPTransport/HTTPTransport.ts
> +type HTTPMethod = (url: string, options?: OptionsWithoutMethod) => Promise<unknown>
done

2023-01-14 10:12 UTC, podlovchenko commented
Спасибо за правки, работу принимаю)

2023-01-14 18:33 UTC, merged